### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'PLANET/PLANET.param'

### ISSUE THREAD

**Issue by gmf12** [ComputArtCMCG/PLANET#2]
Hi,

I was wondering if you could help me with this problem. I installed it on center Linux, however, when I was running the test (PLANET_run.py -p adrb2.pdb -l adrb2_ligand.sdf -m mols.sdf) return with this erro: 

Traceback (most recent call last):
  File "PLANET_run.py", line 172, in <module>
    predicted_affinities,mol_names,smis = workflow(protein_pdb,mol_file,ligand_sdf,centeriod_x,centeriod_y,centeriod_z)
  File "PLANET_run.py", line 102, in workflow
    estimator = PlanetEstimator(device)
  File "PLANET_run.py", line 12, in __init__
    self.model.load_parameters()
  File "/home/gmf/PLANET/PLANET_model.py", line 91, in load_parameters
    self.load_state_dict(torch.load(parameters,map_location=self.device))
  File "/home/gmf/anaconda3/envs/planet/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/gmf/anaconda3/envs/planet/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/gmf/anaconda3/envs/planet/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'PLANET/PLANET.param'

Thank you for your code and support.

Best,
Glaucio

**Comment by aquilazhang** [comment]
Hello! It is my mistake to upload a previous version of the file "PLANET_model.py". I have updated the code, or you can open this file and go to line 90 and replace the origin line to "def load_parameters(self,parameters=os.path.join(os.path.dirname(os.path.abspath(__file__)),'PLANET.param')):"
This will resovle this issue. Thanks for your test!

**Comment by aquilazhang** [comment]
Hello! It is my mistake to upload a previous version of the file "PLANET_model.py". I have updated the code, or you can open this file and go to line 90 and replace the origin line to "def load_parameters(self,parameters=os.path.join(os.path.dirname(os.path.abspath(__file__)),'PLANET.param')):"
This will resovle this issue. Thanks for your test!

**Comment by gmf12** [comment]
Hi Zhang,

It works! Thank you for your support and help. However, I have a doubt when preparing the files to run PLANET. In -l I must put the file with coordinates from docking studies or just put the PLANET to running a docking pose as well? Do you have some tutorials on how to prepare these files?

Best,
Glaucio

**Comment by aquilazhang** [comment]
Dear Glaucio，
        
            
        
    PLANET does not require ligand coordinates. It directly predicts binding affinity based on 2D molecule structures. Thus, there is no need to preprocess ligand files. Both 2D .sdf and SMILES (.smi) works.But, if you want to use PLANET to rank docked poses, I suggest that maybe PLANET is not a good choice. As you can see in the article, the docking power of PLANET is in middle class. PLANET was not designed for this purpose at the beginning and we do not provide the code for ranking poses. Sorry for that.Hope these can help with you~Zhang, Xiangying
         
        
            
                        张翔鹰Fudan ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/22/2023 18:55
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Xiangying ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [ComputArtCMCG/PLANET] FileNotFoundError: [Errno 2] No such file or directory: 'PLANET/PLANET.param' (Issue #2)
        
      
    
  

Hi Zhang,
It works! Thank you for your support and help. However, I have a doubt when preparing the files to run PLANET. In -l I must put the file with coordinates from docking studies or just put the PLANET to running a docking pose as well? Do you have some tutorials on how to prepare these files?
Best,
Glaucio
