### ISSUE TITLE
Issue when trying to utilize the PLANET project in Google Colab

### ISSUE THREAD

**Issue by SHKimKim** [ComputArtCMCG/PLANET#4]
Hello, aquilazhang

I'm glad that PLANET is a program that is easy to use and precise. 
However, I've been trying to utilize the PLANET project in Google Colab and have encountered some issues that I'm unable to resolve. Here are the steps I followed and the error message I received:

I set up the environment with no issues using:

!conda env create -f planet.yaml
!conda activate planet

However, when I attempt to run the script:

!python PLANET_run.py -p adrb2.pdb -l adrb2_ligand.sdf -m mols.sdf

I receive the following traceback:

Traceback (most recent call last):
  File "/content/PLANET_run.py", line 19, in set_pocket_from_ligand
    self.pocket = ProteinPocket(protein_pdb=protein_pdb,ligand_sdf=ligand_sdf)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/chemutils.py", line 95, in __init__
    ligand = Mol(Chem.SDMolSupplier(ligand_sdf,sanitize=False)[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: File error: Bad input file adrb2_ligand.sdf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PLANET_run.py", line 174, in <module>
    predicted_affinities,mol_names,smis = workflow(protein_pdb,mol_file,ligand_sdf,centeriod_x,centeriod_y,centeriod_z)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/PLANET_run.py", line 107, in workflow
    estimator.set_pocket_from_ligand(protein_pdb,ligand_sdf)
  File "/content/PLANET_run.py", line 21, in set_pocket_from_ligand
    raise RuntimeError('the protein pdb file need to be fixed')
RuntimeError: the protein pdb file need to be fixed

This error persists even after replacing the adrb2.pdb and adrb2_ligand.sdf files with ones downloaded directly from the PDB and PubChem. In this situation, I do not know what should I do. 

Could you provide any advice or guidance on resolving this issue? Any insights or suggestions would be greatly appreciated.

Thank you for your time and consideration.

Shanghyeon Kim

**Comment by SHKimKim** [comment]
Hello aquilazhang,

Thank you for your prompt response. I apologize for posting this reply two weeks late. It took me two weeks to get approval for registration with Schrödinger!
Once registered, I see that Schrödinger offers a variety of software options like Phase and Glide. Could you please inform me which software I should use to prepare the protein structure?

Thank you for your time and consideration.

Shanghyeon Kim

**Comment by aquilazhang** [comment]
Hello, Kim:
The 'protein preparation wizard' in  Schrödinger is an easy-to-use tool for protein structure preparation. You may try it out~

**Comment by SHKimKim** [comment]
Oh, it's resolved. I realized my problem after seeing the conversations in the above thread. It turns out that when I need to run the command in colab, I need to specify the content directory as following 

%cd /content/PLANET/demo
!python ../PLANET_run.py -p adrb2.pdb -l adrb2_ligand.sdf -m mols.sdf

Sincerely thank you for your help! 
Shanghyeon Kim
