### ISSUE TITLE
the protein pdb file need to be fixed

### ISSUE THREAD

**Issue by wangjx22** [ComputArtCMCG/PLANET#5]
Dear authors,
I have an issue when running the script "python3.6 ../PLANET_run.py -p adrb2.pdb -l adrb2_ligand.sdf -m mols.sdf".
The error is "the protein pdb file need to be fixed" in line 21 of PLANET_run.py
Could you help me to solve this problem.

yours,
Jinxian

**Comment by aquilazhang** [comment]
Hello, Jinxian:
This issue  happens when the protein structure (.pdb) is incomplete (missing alpha-carbon atoms). You need to prepare the protein structure with other third-party software.

**Comment by wangjx22** [comment]
Thanks for your reply.
Could you send me complete data like a protein or a molecule to run the code successfully?
My email is wangjx22@m.fudan.edu.cn.

yours,
Jinxian

**Comment by aquilazhang** [comment]
The files in 'demo' folder can be run successfully. Please provide a full traceback to let me see what happens.

**Comment by wangjx22** [comment]
I use the demo to run the script "python3.6 ../PLANET_run.py -p adrb2.pdb -l adrb2_ligand.sdf -m mols.sdf".
But have an error:
Traceback (most recent call last):
  File "/remote-home/jinxianwang/code/PLANET-main/PLANET_run.py", line 19, in set_pocket_from_ligand
    self.pocket = ProteinPocket(protein_pdb=protein_pdb,ligand_sdf=ligand_sdf)
  File "/remote-home/jinxianwang/code/PLANET-main/chemutils.py", line 95, in __init__
    ligand = Mol(Chem.SDMolSupplier(ligand_sdf,sanitize=False)[0])
OSError: File error: Bad input file adrb2_ligand.sdf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/remote-home/jinxianwang/code/PLANET-main/PLANET_run.py", line 174, in <module>
    predicted_affinities,mol_names,smis = workflow(protein_pdb,mol_file,ligand_sdf,centeriod_x,centeriod_y,centeriod_z)
  File "/remote-home/jinxianwang/code/PLANET-main/PLANET_run.py", line 107, in workflow
    estimator.set_pocket_from_ligand(protein_pdb,ligand_sdf)
  File "/remote-home/jinxianwang/code/PLANET-main/PLANET_run.py", line 21, in set_pocket_from_ligand
    raise RuntimeError('the protein pdb file need to be fixed')
RuntimeError: the protein pdb file need to be fixed

**Comment by aquilazhang** [comment]
Did you enter the 'demo' dir before running the above command? Or you can run the script with absolute path of required files.

**Comment by wangjx22** [comment]
Thanks for your help.
I can run the code now, however, I want to test new molecules. Which .py file could transform molecules into an SDF file?

Yours
Jinxian

**Comment by aquilazhang** [comment]
There is no script for  transforming  molecules into an SDF file in this repository. The transformation is usually performed with OpenBabel  or other softwares for molecule modeling.

**Comment by wangjx22** [comment]
I have noticed that class VS_SMI_Dataset in PLANET_run.py. So, we also can input the SMILES of molecules? Is it possible to provide input file format in SMILES?

**Comment by aquilazhang** [comment]
Yes, that's right~  Molecules in SMILES format also works

**Comment by wangjx22** [comment]
I have tested my protein, but have 2 errors.
the first is 
Traceback (most recent call last):
  File "/remote-home/jinxianwang/code/PLANET-main/demo/../PLANET_run.py", line 19, in set_pocket_from_ligand
    self.pocket = ProteinPocket(protein_pdb=protein_pdb,ligand_sdf=ligand_sdf)
  File "/remote-home/jinxianwang/code/PLANET-main/chemutils.py", line 100, in __init__
    self.res_features = torch.from_numpy(np.concatenate([residue.get_feature() for residue in self.pocket_residues],axis=0))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate

The second is 
Traceback (most recent call last):
  File "/remote-home/jinxianwang/code/PLANET-main/demo/../PLANET_run.py", line 182, in <module>
    predicted_affinities,mol_names,smis = workflow(protein_pdb,mol_file,ligand_sdf,centeriod_x,centeriod_y,centeriod_z)
  File "/remote-home/jinxianwang/code/PLANET-main/demo/../PLANET_run.py", line 107, in workflow
    estimator.set_pocket_from_ligand(protein_pdb,ligand_sdf)
  File "/remote-home/jinxianwang/code/PLANET-main/demo/../PLANET_run.py", line 21, in set_pocket_from_ligand
    raise RuntimeError('the protein pdb file need to be fixed')
RuntimeError: the protein pdb file need to be fixed

I have pasted the protein file
[4kcd.pdb.gz](https://github.com/ComputArtCMCG/PLANET/files/14050608/4kcd.pdb.gz)
, could you help me to check what problem in my file.

**Comment by aquilazhang** [comment]
I have prepared the protein structure, you can try it out. (unzip it first
[4kcd_prepared.zip](https://github.com/ComputArtCMCG/PLANET/files/14050679/4kcd_prepared.zip)
)

**Comment by wangjx22** [comment]
thanks for your help.
But, I have the same errors using the prepared protein.

**Comment by aquilazhang** [comment]
Did you unzip the file? Besides, since you may have trouble in transforming a molecule file into SDF, how did you assign the flag "-l"? Or, you may use the "-x" "-y" "-z" instead of "-l". But I am not sure if you have defined the pocket center correctly.

**Comment by wangjx22** [comment]
I am sure unzip the file. I using the 4kcd_prepared.pdb you given to me and mols.sdf in your demo as the input of model. And I did not assign the fiag "-I". 
I use the script: python ../PLANET_run.py -p 4kcd_prepared.pdb -m mols.sdf

**Comment by aquilazhang** [comment]
The pocket center is required by PLANET to extract pocket residues from given PDB structure, which is defined as the mass center of molecule through "-l" flag. Or, specify the coordinate of pocket center through "-x" "-y" "-z".

**Comment by wangjx22** [comment]
The adrb2_ligand.sdf is necessary?  I found adrb2_ligand.sdf is a crystal ligand file for determining binding pocket.
If a protein have multi binding pocket, so the adrb2_ligand.sdf should include multi molecules?

**Comment by aquilazhang** [comment]
It is necessary.  The SDF file to define pocket should contain only ONE molecule. For multi-pockets,  you need to specify one pocket and run PLANET at a time and do this for several rounds .
