### ISSUE TITLE
Problem:Tensors must have same number of dimensions: got 2 and 3

### ISSUE THREAD

**Issue by AIM132** [ComputArtCMCG/PLANET#6]
I encountered the following error while running the program. How can I resolve it? Thanks

Traceback (most recent call last):
  File "../../../PLANET_run.py", line 174, in <module>
    predicted_affinities,mol_names,smis = workflow(protein_pdb,mol_file,ligand_sdf,centeriod_x,centeriod_y,centeriod_z)
  File "../../../PLANET_run.py", line 109, in workflow
    estimator.set_pocket_from_coordinate(protein_pdb,centeriod_x,centeriod_y,centeriod_z)
  File "../../../PLANET_run.py", line 29, in set_pocket_from_coordinate
    self.res_features = self.model.cal_res_features_helper(self.pocket.res_features,self.pocket.alpha_coordinates)
  File "/home/liyixiang/PLANET-main/PLANET_model.py", line 97, in cal_res_features_helper
    fresidues = self.proteinegnn.pre_cal_res_features(fresidues,coordinates)
  File "/home/liyixiang/PLANET-main/layers.py", line 305, in pre_cal_res_features
    ],dim=-1)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3

**Comment by aquilazhang** [comment]
This happens when your protein structure is not read correctly by PLANET.  You may need check the protein structure. 
Or, the you may input an inappropriate command. Please make sure you have unserstand the example in demo.

**Comment by AIM132** [comment]
I also report the same error when using the protein file provided by the DUD dataset

**Comment by AIM132** [comment]
I tried PDBfixer and SPDBV, but neither of them had any effect

**Comment by aquilazhang** [comment]
Would you show me the command?

**Comment by AIM132** [comment]
Thank you for your persistent answer. It may be that there was an issue with my command. Once again, thank you

**Comment by AIM132** [comment]
But I found that there are still some structures that have been fixed by PDBFixer and still report the error 'protein need fix'

**Comment by aquilazhang** [comment]
PDBFixer may not fix residues missing alpha-carbon. You may try other softwares for molecule modeling.

**Comment by AIM132** [comment]
ok,thanks
